/* Starter roster generated from 2026.05.14 Scoring Sheet.xlsx (Summary + Instructions tabs).
   Edit in the Admin page after loading — this file is only the starting point. */
export const SEED_PLAYERS = [
 {
  "id": "alain_patry",
  "name": "Alain PATRY",
  "short": "Alain P",
  "gender": "M",
  "team": 1,
  "order": 0,
  "spare": false,
  "dummy": false,
  "active": true
 },
 {
  "id": "mike_hood",
  "name": "Mike HOOD",
  "short": "Mike H",
  "gender": "M",
  "team": 1,
  "order": 1,
  "spare": false,
  "dummy": false,
  "active": true
 },
 {
  "id": "sherley_demers",
  "name": "Sherley DEMERS",
  "short": "Sherley D",
  "gender": "F",
  "team": 1,
  "order": 2,
  "spare": false,
  "dummy": false,
  "active": true
 },
 {
  "id": "michael_doyle",
  "name": "Michael DOYLE",
  "short": "Michael D",
  "gender": "M",
  "team": 2,
  "order": 3,
  "spare": false,
  "dummy": false,
  "active": true
 },
 {
  "id": "terry_woodard",
  "name": "Terry WOODARD",
  "short": "Terry W",
  "gender": "F",
  "team": 2,
  "order": 4,
  "spare": false,
  "dummy": false,
  "active": true
 },
 {
  "id": "ter_lamarche",
  "name": "Ter LAMARCHE",
  "short": "Ter L",
  "gender": "F",
  "team": 2,
  "order": 5,
  "spare": false,
  "dummy": false,
  "active": true
 },
 {
  "id": "ian_campbell_s_best",
  "name": "(Ian) CAMPBELL's Best",
  "short": "Ian B",
  "gender": "M",
  "team": 3,
  "order": 6,
  "spare": false,
  "dummy": false,
  "active": true
 },
 {
  "id": "diana_bussiere",
  "name": "Diana BUSSIERE",
  "short": "Diana B",
  "gender": "F",
  "team": 3,
  "order": 7,
  "spare": false,
  "dummy": false,
  "active": true
 },
 {
  "id": "heather_leeks",
  "name": "Heather LEEKS",
  "short": "Heather L",
  "gender": "F",
  "team": 3,
  "order": 8,
  "spare": false,
  "dummy": false,
  "active": true
 },
 {
  "id": "brent_caves",
  "name": "Brent CAVES",
  "short": "Brent C",
  "gender": "M",
  "team": 4,
  "order": 9,
  "spare": false,
  "dummy": false,
  "active": true
 },
 {
  "id": "susan_doyle",
  "name": "Susan DOYLE",
  "short": "Susan D",
  "gender": "F",
  "team": 4,
  "order": 10,
  "spare": false,
  "dummy": false,
  "active": true
 },
 {
  "id": "sherri_caves",
  "name": "Sherri CAVES",
  "short": "Sherri C",
  "gender": "F",
  "team": 4,
  "order": 11,
  "spare": false,
  "dummy": false,
  "active": true
 },
 {
  "id": "ken_mclean",
  "name": "Ken MCLEAN",
  "short": "Ken M",
  "gender": "M",
  "team": 5,
  "order": 12,
  "spare": false,
  "dummy": false,
  "active": true
 },
 {
  "id": "shannon_peters",
  "name": "Shannon PETERS",
  "short": "Shannon P",
  "gender": "F",
  "team": 5,
  "order": 13,
  "spare": false,
  "dummy": false,
  "active": true
 },
 {
  "id": "linda_mattinson",
  "name": "Linda MATTINSON",
  "short": "Linda M",
  "gender": "F",
  "team": 5,
  "order": 14,
  "spare": false,
  "dummy": false,
  "active": true
 },
 {
  "id": "rob_gosse",
  "name": "Rob GOSSE",
  "short": "Rob G",
  "gender": "M",
  "team": 6,
  "order": 15,
  "spare": false,
  "dummy": false,
  "active": true
 },
 {
  "id": "francine_lacelle",
  "name": "Francine LACELLE",
  "short": "Francine L",
  "gender": "F",
  "team": 6,
  "order": 16,
  "spare": false,
  "dummy": false,
  "active": true
 },
 {
  "id": "harmonie_baxter",
  "name": "Harmonie BAXTER",
  "short": "Harmonie B",
  "gender": "F",
  "team": 6,
  "order": 17,
  "spare": false,
  "dummy": false,
  "active": true
 },
 {
  "id": "alain_bussiere",
  "name": "Alain BUSSIERE",
  "short": "Alain B",
  "gender": "M",
  "team": 7,
  "order": 18,
  "spare": false,
  "dummy": false,
  "active": true
 },
 {
  "id": "kristine_sauve",
  "name": "Kristine SAUVE",
  "short": "Kristine S",
  "gender": "F",
  "team": 7,
  "order": 19,
  "spare": false,
  "dummy": false,
  "active": true
 },
 {
  "id": "steve_daly",
  "name": "Steve DALY",
  "short": "Steve D",
  "gender": "M",
  "team": 7,
  "order": 20,
  "spare": false,
  "dummy": false,
  "active": true
 },
 {
  "id": "shawn_pritchard",
  "name": "Shawn PRITCHARD",
  "short": "Shawn P",
  "gender": "M",
  "team": 8,
  "order": 21,
  "spare": false,
  "dummy": false,
  "active": true
 },
 {
  "id": "andre_gaudet",
  "name": "Andre GAUDET",
  "short": "Andre G",
  "gender": "M",
  "team": 8,
  "order": 22,
  "spare": false,
  "dummy": false,
  "active": true
 },
 {
  "id": "charmaine_sutton",
  "name": "Charmaine SUTTON",
  "short": "Charmaine S",
  "gender": "F",
  "team": 8,
  "order": 23,
  "spare": false,
  "dummy": false,
  "active": true
 },
 {
  "id": "justin_vallieres",
  "name": "Justin VALLIERES",
  "short": "Justin V",
  "gender": "M",
  "team": 9,
  "order": 24,
  "spare": false,
  "dummy": false,
  "active": true
 },
 {
  "id": "rachel_jeffries",
  "name": "Rachel JEFFRIES",
  "short": "Rachel J",
  "gender": "F",
  "team": 9,
  "order": 25,
  "spare": false,
  "dummy": false,
  "active": true
 },
 {
  "id": "katie_smith",
  "name": "Katie SMITH",
  "short": "Katie S",
  "gender": "F",
  "team": 9,
  "order": 26,
  "spare": false,
  "dummy": false,
  "active": true
 },
 {
  "id": "mike_western",
  "name": "Mike WESTERN",
  "short": "Mike W",
  "gender": "M",
  "team": 10,
  "order": 27,
  "spare": false,
  "dummy": false,
  "active": true
 },
 {
  "id": "lynn_soural",
  "name": "Lynn SOURAL",
  "short": "Lynn S",
  "gender": "F",
  "team": 10,
  "order": 28,
  "spare": false,
  "dummy": false,
  "active": true
 },
 {
  "id": "maggie_joanisse",
  "name": "Maggie JOANISSE",
  "short": "Maggie J",
  "gender": "F",
  "team": 10,
  "order": 29,
  "spare": false,
  "dummy": false,
  "active": true
 },
 {
  "id": "tom_mercer",
  "name": "Tom MERCER",
  "short": "Tom M",
  "gender": "M",
  "team": 11,
  "order": 30,
  "spare": false,
  "dummy": false,
  "active": true
 },
 {
  "id": "bruce_branch",
  "name": "Bruce BRANCH",
  "short": "Bruce B",
  "gender": "M",
  "team": 11,
  "order": 31,
  "spare": false,
  "dummy": false,
  "active": true
 },
 {
  "id": "val_turcotte",
  "name": "Val TURCOTTE",
  "short": "Val T",
  "gender": "F",
  "team": 11,
  "order": 32,
  "spare": false,
  "dummy": false,
  "active": true
 },
 {
  "id": "mike_goodfellow",
  "name": "Mike GOODFELLOW",
  "short": "Mike G",
  "gender": "M",
  "team": 12,
  "order": 33,
  "spare": false,
  "dummy": false,
  "active": true
 },
 {
  "id": "kim_wanner_bell",
  "name": "Kim WANNER BELL",
  "short": "Kim WB",
  "gender": "F",
  "team": 12,
  "order": 34,
  "spare": false,
  "dummy": false,
  "active": true
 },
 {
  "id": "diane_cote",
  "name": "Diane COTE",
  "short": "Diane C",
  "gender": "F",
  "team": 12,
  "order": 35,
  "spare": false,
  "dummy": false,
  "active": true
 },
 {
  "id": "dwayne_smith",
  "name": "Dwayne SMITH",
  "short": "Dwayne S",
  "gender": "M",
  "team": 13,
  "order": 36,
  "spare": false,
  "dummy": false,
  "active": true
 },
 {
  "id": "bogdan_sburlea",
  "name": "Bogdan SBURLEA",
  "short": "Bogdan S",
  "gender": "M",
  "team": 13,
  "order": 37,
  "spare": false,
  "dummy": false,
  "active": true
 },
 {
  "id": "monique_proulx",
  "name": "Monique PROULX",
  "short": "Monique P",
  "gender": "F",
  "team": 13,
  "order": 38,
  "spare": false,
  "dummy": false,
  "active": true
 },
 {
  "id": "gaeten_laurin",
  "name": "Gaeten LAURIN",
  "short": "Gaeten L",
  "gender": "M",
  "team": 14,
  "order": 39,
  "spare": false,
  "dummy": false,
  "active": true
 },
 {
  "id": "marcy_tremblay",
  "name": "Marcy TREMBLAY",
  "short": "Marcy T",
  "gender": "F",
  "team": 14,
  "order": 40,
  "spare": false,
  "dummy": false,
  "active": true
 },
 {
  "id": "kashifa_siddique",
  "name": "Kashifa SIDDIQUE",
  "short": "Kashifa S",
  "gender": "F",
  "team": 14,
  "order": 41,
  "spare": false,
  "dummy": false,
  "active": true
 },
 {
  "id": "allen_grant",
  "name": "Allen GRANT",
  "short": "Allen G",
  "gender": "M",
  "team": 15,
  "order": 42,
  "spare": false,
  "dummy": false,
  "active": true
 },
 {
  "id": "christina_sutton",
  "name": "Christina SUTTON",
  "short": "Christina S",
  "gender": "F",
  "team": 15,
  "order": 43,
  "spare": false,
  "dummy": false,
  "active": true
 },
 {
  "id": "andre_richer",
  "name": "Andre RICHER",
  "short": "Andre R",
  "gender": "M",
  "team": 15,
  "order": 44,
  "spare": false,
  "dummy": false,
  "active": true
 },
 {
  "id": "jeff_stevenson",
  "name": "Jeff STEVENSON",
  "short": "Jeff S",
  "gender": "M",
  "team": 16,
  "order": 45,
  "spare": false,
  "dummy": false,
  "active": true
 },
 {
  "id": "sarah_foster",
  "name": "Sarah FOSTER",
  "short": "Sarah F",
  "gender": "F",
  "team": 16,
  "order": 46,
  "spare": false,
  "dummy": false,
  "active": true
 },
 {
  "id": "suzanne_sauve",
  "name": "Suzanne SAUVE",
  "short": "Suzanne S",
  "gender": "F",
  "team": 16,
  "order": 47,
  "spare": false,
  "dummy": false,
  "active": true
 },
 {
  "id": "s_lois_grant",
  "name": "S. Lois Grant",
  "short": "S. Lois Grant",
  "gender": "N",
  "team": null,
  "order": 900,
  "spare": true,
  "dummy": false,
  "active": true
 },
 {
  "id": "s_jason_huard",
  "name": "S. Jason Huard",
  "short": "S. Jason Huard",
  "gender": "N",
  "team": null,
  "order": 900,
  "spare": true,
  "dummy": false,
  "active": true
 },
 {
  "id": "s_marie_legault",
  "name": "S. Marie Legault",
  "short": "S. Marie Legault",
  "gender": "N",
  "team": null,
  "order": 900,
  "spare": true,
  "dummy": false,
  "active": true
 },
 {
  "id": "s_janis_parry_hood",
  "name": "S. Janis Parry-Hood",
  "short": "S. Janis Parry-Hood",
  "gender": "N",
  "team": null,
  "order": 900,
  "spare": true,
  "dummy": false,
  "active": true
 },
 {
  "id": "s_tracey_davey",
  "name": "S. Tracey Davey",
  "short": "S. Tracey Davey",
  "gender": "N",
  "team": null,
  "order": 900,
  "spare": true,
  "dummy": false,
  "active": true
 },
 {
  "id": "s_paul_lamarche",
  "name": "S. Paul Lamarche",
  "short": "S. Paul Lamarche",
  "gender": "N",
  "team": null,
  "order": 900,
  "spare": true,
  "dummy": false,
  "active": true
 },
 {
  "id": "s_chantal_desjardins",
  "name": "S. Chantal Desjardins",
  "short": "S. Chantal Desjardins",
  "gender": "N",
  "team": null,
  "order": 900,
  "spare": true,
  "dummy": false,
  "active": true
 },
 {
  "id": "s_jp_fauvelle",
  "name": "S. JP Fauvelle",
  "short": "S. JP Fauvelle",
  "gender": "N",
  "team": null,
  "order": 900,
  "spare": true,
  "dummy": false,
  "active": true
 },
 {
  "id": "s_annick_louis_seize",
  "name": "S. Annick Louis-Seize",
  "short": "S. Annick Louis-Seize",
  "gender": "N",
  "team": null,
  "order": 900,
  "spare": true,
  "dummy": false,
  "active": true
 },
 {
  "id": "s_paul_beaudoin",
  "name": "S. Paul Beaudoin",
  "short": "S. Paul Beaudoin",
  "gender": "N",
  "team": null,
  "order": 900,
  "spare": true,
  "dummy": false,
  "active": true
 },
 {
  "id": "s_greg_parent",
  "name": "S. Greg Parent",
  "short": "S. Greg Parent",
  "gender": "N",
  "team": null,
  "order": 900,
  "spare": true,
  "dummy": false,
  "active": true
 },
 {
  "id": "s_veronica_house",
  "name": "S. Veronica House",
  "short": "S. Veronica House",
  "gender": "N",
  "team": null,
  "order": 900,
  "spare": true,
  "dummy": false,
  "active": true
 },
 {
  "id": "s_justin_maundrell",
  "name": "S. Justin Maundrell",
  "short": "S. Justin Maundrell",
  "gender": "N",
  "team": null,
  "order": 900,
  "spare": true,
  "dummy": false,
  "active": true
 },
 {
  "id": "s_heather_cracknell",
  "name": "S. Heather Cracknell",
  "short": "S. Heather Cracknell",
  "gender": "N",
  "team": null,
  "order": 900,
  "spare": true,
  "dummy": false,
  "active": true
 },
 {
  "id": "s_roger_smith",
  "name": "S. Roger Smith",
  "short": "S. Roger Smith",
  "gender": "N",
  "team": null,
  "order": 900,
  "spare": true,
  "dummy": false,
  "active": true
 },
 {
  "id": "s_ray_nault",
  "name": "S. Ray Nault",
  "short": "S. Ray Nault",
  "gender": "N",
  "team": null,
  "order": 900,
  "spare": true,
  "dummy": false,
  "active": true
 },
 {
  "id": "s_ray_lloyd",
  "name": "S. Ray Lloyd",
  "short": "S. Ray Lloyd",
  "gender": "N",
  "team": null,
  "order": 900,
  "spare": true,
  "dummy": false,
  "active": true
 },
 {
  "id": "s_richard",
  "name": "S. Richard (?)",
  "short": "S. Richard (?)",
  "gender": "N",
  "team": null,
  "order": 900,
  "spare": true,
  "dummy": false,
  "active": true
 },
 {
  "id": "s_stephan_cantin",
  "name": "S. Stephan Cantin",
  "short": "S. Stephan Cantin",
  "gender": "N",
  "team": null,
  "order": 900,
  "spare": true,
  "dummy": false,
  "active": true
 },
 {
  "id": "s_mike_western",
  "name": "S. Mike Western",
  "short": "S. Mike Western",
  "gender": "N",
  "team": null,
  "order": 900,
  "spare": true,
  "dummy": false,
  "active": true
 },
 {
  "id": "s_andy_mccauley",
  "name": "S. Andy McCauley",
  "short": "S. Andy McCauley",
  "gender": "N",
  "team": null,
  "order": 900,
  "spare": true,
  "dummy": false,
  "active": true
 },
 {
  "id": "s_gilles_martin",
  "name": "S. Gilles Martin",
  "short": "S. Gilles Martin",
  "gender": "N",
  "team": null,
  "order": 900,
  "spare": true,
  "dummy": false,
  "active": true
 },
 {
  "id": "s_paul_awalt",
  "name": "S. Paul Awalt",
  "short": "S. Paul Awalt",
  "gender": "N",
  "team": null,
  "order": 900,
  "spare": true,
  "dummy": false,
  "active": true
 },
 {
  "id": "s_ben_lalonde",
  "name": "S. Ben Lalonde",
  "short": "S. Ben Lalonde",
  "gender": "N",
  "team": null,
  "order": 900,
  "spare": true,
  "dummy": false,
  "active": true
 },
 {
  "id": "s_charles_wootton",
  "name": "S. Charles Wootton",
  "short": "S. Charles Wootton",
  "gender": "N",
  "team": null,
  "order": 900,
  "spare": true,
  "dummy": false,
  "active": true
 },
 {
  "id": "s_kathy_barnaby",
  "name": "S. Kathy Barnaby",
  "short": "S. Kathy Barnaby",
  "gender": "N",
  "team": null,
  "order": 900,
  "spare": true,
  "dummy": false,
  "active": true
 },
 {
  "id": "s_sky_parker",
  "name": "S. Sky Parker",
  "short": "S. Sky Parker",
  "gender": "N",
  "team": null,
  "order": 900,
  "spare": true,
  "dummy": false,
  "active": true
 },
 {
  "id": "s_karen_mcgregor",
  "name": "S. Karen McGregor",
  "short": "S. Karen McGregor",
  "gender": "N",
  "team": null,
  "order": 900,
  "spare": true,
  "dummy": false,
  "active": true
 },
 {
  "id": "s_miriam_ranger",
  "name": "S. Miriam Ranger",
  "short": "S. Miriam Ranger",
  "gender": "N",
  "team": null,
  "order": 900,
  "spare": true,
  "dummy": false,
  "active": true
 },
 {
  "id": "s_devon_wadden",
  "name": "S. Devon Wadden",
  "short": "S. Devon Wadden",
  "gender": "N",
  "team": null,
  "order": 900,
  "spare": true,
  "dummy": false,
  "active": true
 },
 {
  "id": "s_ihad_balaa",
  "name": "S. Ihad Balaa",
  "short": "S. Ihad Balaa",
  "gender": "N",
  "team": null,
  "order": 900,
  "spare": true,
  "dummy": false,
  "active": true
 },
 {
  "id": "s_alex_janis_co_worker",
  "name": "S. Alex (Janis co-worker)",
  "short": "S. Alex (Janis co-worker)",
  "gender": "N",
  "team": null,
  "order": 900,
  "spare": true,
  "dummy": false,
  "active": true
 },
 {
  "id": "dummy",
  "name": "Dummy",
  "short": "Dummy",
  "gender": "N",
  "team": null,
  "order": 999,
  "spare": true,
  "dummy": true,
  "active": true
 }
];

// Tonight's pairings from your data.json (used to pre-fill the demo night)
export const SEED_PAIRINGS = [[9, 10], [1, 3], [8, 11], [2, 16], [7, 12], [4, 15], [6, 13], [5, 14]];
